---
engine: knitr
filters: 
  - webr
---
<!-- CONTENT -->

# AR och MA modeller

Hur kan en tidsserie utan en tydlig trend eller säsongsmönster modelleras? Vi kan på olika sätt ta tillvara på tidsberoendet i serien genom **autoregressiva** (AR) processer som innebär regression "på sig själv" och genom **glidande medelvärde** (MA) processer som innebär regression på tidigare feltermer.

I detta kapitel kommer dessa två processer att presenteras separat för att i nästa kapitel visa hur de kan sammanfogas till en gemensam modell. Vi kommer titta på hur processerna ser ut i teorin och vilka egenskaper de uppvisar för att lättare kunna identifiera när specifika processer är lämpliga modellval för en observerad serie.

## Autoregressiva processer
 
En autoregressiv process använder beroendet mellan olika tidpunkter som hjälpvariabler i en modell som väldigt mycket liknar en linjär regressionsmodell. Generellt kan vi beskriva en AR(p)-process som:
$$
  \begin{aligned}
  Y_t = \phi_1 Y_{t-1} + \phi_2 Y_{t-2} + \dots + \phi_p Y_{t-p} + e_t
  \end{aligned}
$$ {#eq-arp}
det vill säga att $Y_t$ förklaras av en linjärkombination av $p$ tidigare värden. Vardera $\phi$ (grekiska bokstaven phi^[Uttalas fi.]) beskriver relationen mellan det specifika lagget och den nuvarande tidpunkten. Ett antagande som görs är att alla $Y_t$ är oberoende från $e_t$ där $e_t$ betraktas som den information som de tidigare observerade tidpunkterna inte lyckas förklara. Detta fel antas $N(0, \sigma^2_e)$. 

I @eq-arp antas att $E[Y_t] = 0$ men vi kan enkelt utöka modellen till att ha $\mu$ som medelvärde genom att formulera $Y_t - \mu$ i vänsterledet (och för alla andra förekomster av $Y_{t-k}$. Genomgående i dessa kapitel kommer vi anta att väntevärdet är 0 men @cryer2008 visar varianter när väntevärdet är nollskild.

<!-- TODO WHERE TO PUT 4.1/4.2? MAYBE SOMETHING IN RELATION TO THE MA PROCESS LAST IN THIS CHAPTER -->

### AR(1)

Den enklaste formen av en autoregressiv modell är en AR(1):
$$
  \begin{aligned}
  Y_t = \phi Y_{t-1} + e_t
  \end{aligned}
$$ {#eq-ar1}

Denna modell antar att $Y_t$ endast beror på den föregående tidpunkten och ett slumpfel. Detta slumpfel kan beskrivas som den nya informationen som nuvarande tidpunkt introducerar till serien.

Vi kan simulera hur en AR(1) ser ut för olika värden på $\phi$.

<!-- QUESTION: ÄR DETTA RELEVANT ELLER SKA VI ANVÄNDA INBYGGDA FUNKTIONER SÅSOM arima.sim() ISTÄLLET? -->

```{webr-r}
#| fig-width: 5
#| fig-height: 3
#| fig-cap: Simulerad AR(1) serie från angivet phi
#| out-width: "90%"
#| autorun: true

# Skapar en funktion för att simulera en AR(1) process
ar1 <- function(phi, n) {
  y <- numeric()
  
  for (i in seq_len(n)) {
    if (t == 1) {
      y[t] <- rnorm(n = 1)
    } else {
      y[t] <- phi * y[t-1] + rnorm(n = 1)
    }
  }
  
  y
}

# Egenskaper för simuleringen
n <- 100
phi <- 0.9

# Visualisera serien i ett linjediagram
tibble(
  t = seq_len(n),
  yt = ar1(phi = phi, n = n)
) |> 
  ggplot() + aes(x = t, y = yt) + geom_line() + 
  theme_bw()
```

En av serierna vi tittade på i föregående kapitel, Random Walk i @eq-random-walk, är ett specialfall av en AR(1) process när $\phi = 1$. Vi bedömde dock tidigare att en Random Walk *inte* var en stationär serie så hur kan vi säkerställa att en AR-process uppfyller stationäritet? I just detta fall, hur behöver vi begränsa $\phi$ för att en AR(1) ska anses vara en stationär serie?

Vi kan börja med att beräkna variansen av @eq-ar1:

$$
  \begin{aligned}
  Var(Y_t) = \gamma_0 &= Var(\phi Y_{t-1} + e_t) \\
  \gamma_0 &= \phi^2Var(Y_{t-1}) + Var(e_t) && \text{(pga oberoende)}\\
  \gamma_0 &= \phi^2 \gamma_0 + \sigma^2_e \\
  \gamma_0 &= \frac{\sigma^2_e}{1 - \phi^2}
  \end{aligned}
$$

:::{.callout-note}
Kom ihåg att $\gamma_0 = cov(Y_t, Y_t) = Var(Y_t)$ gäller för alla $Y_{t-k}$ där $k \ge 0$.
:::

Redan vid detta uttryck ser vi några begränsningar som måste göras, nämligen $|\phi| < 1$, för att variansen ska vara definierbar och strikt positiv. Vi kallar detta för seriens **stationäritetsvillkor**.

Autokovariansen för lagg $k$ blir då:

$$
  \begin{aligned}
  \gamma_k = \phi \gamma_{k-1} + E\left[e_t Y_{t-k}\right]
  \end{aligned}
$$
som pga oberoendet mellan $e_t$ och $Y_t$ ger:
$$
  \begin{aligned}
  \gamma_k = \phi \gamma_{k-1}
  \end{aligned}
$$ {#eq-rho-ar1}
för alla $k > 0$.

Vi kan utveckla denna ekvation för att hitta ett annat sätt att formulera autokovariansen.
$$
  \begin{aligned}
    \gamma_1 &= \phi \gamma_0 &&= \phi \frac{\sigma^2_e}{1 - \phi^2}\\
    \gamma_2 &= \phi \gamma_1 &&= \phi \phi \frac{\sigma^2_e}{1 - \phi^2}\\
    &&&= \phi^2 \frac{\sigma^2_e}{1 - \phi^2} \\
    \gamma_3 &= \phi \gamma_2 &&= \phi^3 \frac{\sigma^2_e}{1 - \phi^2}\\
    &&\vdots\\
    \gamma_k & &&= \phi^k \frac{\sigma^2_e}{1 - \phi^2}
  \end{aligned}
$$

Med hjälp av denna formulering kan vi reducera autokorrelationen till:

$$
  \begin{aligned}
  \rho_k = \frac{\gamma_k}{\sqrt{\gamma_0 \cdot \gamma_0}} = \frac{\gamma_k}{\gamma_0} = \frac{\phi^k \frac{\sigma^2_e}{1 - \phi^2}}{\frac{\sigma^2_e}{1 - \phi^2}} = \phi^k
  \end{aligned}
$$
det vill säga en exponentiellt minskande korrelation då $|\phi| < 1$. 

Med hjälp av dessa härledningar kan vi visualisera hur $\rho_k$ ser ut för olika värden på $\phi$. När vi senare vill identifiera en lämplig modell kommer vi med hjälp av SAC kunna se skattade autokorrelationer och matcha den observerade seriens beteende till beteendet från en teoretisk modell.

```{webr-r}
#| fig-width: 5
#| fig-height: 3
#| fig-cap: Autokorrelationen för en AR(1) med olika phi
#| out-width: "90%"
#| autorun: true

# Ange ett värde på phi i processen
phi <- 0.5

tibble(
  k = seq_len(20), 
  rho = phi^k
) |> 
  ggplot() + aes(x = k, y = rho) + 
  geom_bar(width = 0.3, stat = "identity") +
  scale_y_continuous(limits = c(-1, 1)) + 
  geom_hline(yintercept = 0, linewidth = 1) +
  labs(y = expression(rho[k])) + 
  theme_bw()

```

Testa att ändra `phi` till olika lämpliga värden, givet $|\phi| < 1$, och se vad som händer med visualiseringen. Testa även negativa tal och se hur det förändrar $\rho_k$.

Figuren visar ett snabbt avtagande mönster till skillnad från det långsamt avtagande, nästan cycliska mönster som Random Walk uppvisade. Detta visar att när vi begränsar $\phi$ enligt dess stationäritetsvilkor blir serien stationär.

### AR(2)

Om vi utökar modellen till att också ta hänsyn till ytterligare en tidigare tidpunkt fås:
$$
  \begin{aligned}
  Y_t = \phi_1 Y_{t-1} + \phi_2 Y_{t-2} + e_t
  \end{aligned}
$$

Vi kan gå igenom liknande härledningar för de olika beskrivande måtten för en AR(2)-process som vi gjorde för AR(1) men det blir snabbt mycket komplicerat. Istället väljer vi i detta läge att visa stationäritetsvillkoren och kan läsa mer om denna härledning i @cryer2008^[sida 72-73 och 84]. 

$$
  \begin{aligned}
  \phi_1 + \phi_2 < 1 \qquad \phi_2 - \phi_1 < 1 \qquad |\phi_2| < 1
  \end{aligned}
$$

Att beräkna autokorrelationen för olika värden på $\phi$ blir också mer komplicerat eftersom vi numera har två variabler men vissa härledningar finns även för en AR(2) i @cryer2008. Med följande kod kan vi justera värden på $\phi_1$ och $\phi_2$ för att beräkna $\rho_k$ utifrån de härledda formlerna.

```{webr-r}
#| fig-width: 5
#| fig-height: 3
#| fig-cap: Autokorrelationen för en AR(2) med olika värden på phi
#| out-width: "90%"
#| autorun: true

rhoAr2 <- function(phi1, phi2) {
  
  # Kontrollerar att stationäritetsvillkoren är uppfyllda
  assert_that(phi1 + phi2 < 1, msg = "phi1 + phi2 är inte < 1")
  assert_that(phi2 - phi1 < 1, msg = "phi2 - phi1 är inte < 1")
  assert_that(abs(phi2) < 1,   msg = "|phi2| är inte < 1")
  
  n <- 20

  # Skapa en tom vektor
  rho <- numeric()
  
  # Beräkna rho med två specialfall för t = 1 och t = 2
  for (t in seq_len(n)) {
    if (t == 1) {
      rho[t] <- phi1 / (1 - phi2)
    } else if (t == 2) {
      rho[t] <- (phi2 * (1 - phi2) + phi1^2) / (1 - phi2)
    } else {
      rho[t] <- phi1 * rho[t-1] + phi2 * rho[t-2]
    }
  }
  
  graph <- 
    tibble(
      k = seq_len(20), 
      rho = rho
    ) |> 
      ggplot() + aes(x = k, y = rho) + 
      geom_bar(width = 0.3, stat = "identity") +
      scale_y_continuous(limits = c(-1, 1)) + 
      geom_hline(yintercept = 0, linewidth = 1) +
      labs(y = expression(rho[k])) + 
      theme_bw()
    
  print(graph)
  
  return(rho)
}

rho <- rhoAr2(phi1 = 0.5, phi2 = 0.25)

```

Testa olika kombinationer av parametrarna och försök att identifiera några trender i modellernas autokorrelation. Notera att funktionen kommer generera ett felmeddelande om stationäritetsantaganden inte uppfylls och modellen inte är lämplig.

<!-- TODO: Matcha par av stationäritetsvillkor för olika serier Edit:?? Vad menar jag med detta??-->

## Glidande medelvärdesprocesser

Istället för att använda det observerade värdet från en föregående tidpunkt kan vi skapa en modell som baseras på den slumpmässiga feltermen från den nuvarande och $q$ tidigare tidpunkter. 

Generellt kan vi beskriva en MA(q) process som:
$$
  \begin{aligned}
  Y_t = e_t + \theta_1 e_{t-1} + \theta_2 e_{t-2} + \dots + \theta_q e_{t-q}
  \end{aligned}
$$ {#eq-maq}
där de olika $\theta$ (grekiska theta^[Uttalas teta eller täta.]) beskriver hur stor effekt respektive tidpunkts felterm har på det nuvarande. En MA-process har inte några stationäritetsvillkor för $\theta$, däremot behöver vi titta närmare på **invertibilitet** i @sec-invertibility.

:::{.callout-note}
Notera att vi ändrar symbolen framför $\theta$ från $-$ till $+$ jämfört med @cryer2008 på grund av att de funktioner vi använder i R använder denna formulering med positiva parametrar. Se dokumentationen för funktionen `stats::arima()` som `TSA`-paketet använder som grund.
:::

### MA(1)

Med endast en term blir modellen: 
$$
  \begin{aligned}
  Y_t = e_t + \theta e_{t-1}
  \end{aligned}
$$ {#eq-ma1}
med följande egenskaper:

$$
  \begin{aligned}
  E[Y_t] &= 0\\
  \\
  Var(Y_t) = \gamma_0 &= Var(e_t + \theta e_{t-1}) \\
  \gamma_0 &= Var(e_t) + \theta^2 Var(e_{t-1}) && \text{(pga oberoende)}\\
  \gamma_0 &= \sigma^2_e + \theta^2 \sigma_e^2 \\
  \gamma_0 &= \sigma^2_e (1 + \theta^2) 
  \end{aligned}
$$

Vi kan också, likt de beskrivande måtten för @sec-moving-average-series, enkelt beräkna fram autokovariansen genom att titta på hur många gemensamma termer som olika lagg har då $e_t$ och $e_s$ antas oberoende när $t \ne s$. För $k = 1$:

$$
  \begin{aligned}
  \gamma_1 &= cov(e_t + \theta e_{t-1}, e_{t-1} + \theta e_{t-2}) \\
  &= cov(\theta e_{t-1}, e_{t-1}) = \theta \sigma^2_e
  \end{aligned}
$$
och $k = 2$:

$$
  \begin{aligned}
  \gamma_2 &= cov(e_t + \theta e_{t-1}, e_{t-2} + \theta e_{t-3}) \\
  &= 0
  \end{aligned}
$$

Detta betyder att för alla lagg $k \ge 2$ är autokovariansen, och sedermera autokorrelationen, 0: 

$$
  \begin{aligned}
  \rho_k = \begin{cases}
    \frac{\theta}{1 + \theta^2} &\text{om } k = 1\\
    0 &\text{om } k \ge 2
  \end{cases}
  \end{aligned}
$$

<!-- TODO Visualization of the rho for MA1 -->

### Invertibilitet {#sec-invertibility}
När vi beräknar autokorrelationen för en MA-process ser vi att både $\theta$ och $1 / \theta$ ger samma värde, vilket blir ett problem när vi ska anpassa modellen. Vi kan visa att en MA-process kan **inverteras** till en oändlig serie av tidigare tidpunkter, likt en AR-process, om och endast om $|\theta| < 1$ för en MA(1) och för en generell MA(q) liknande krav på $\theta$ som för en generell AR(p). 

Vi kräver både stationäritet och invertibilitet för alla modeller som inkluderar en MA-komponent. 
[TODO: SHOW AR as an infinite MA series in an earlier chapter to make this make sense]{style="color: red"}

### MA(2)

En MA(2) process definieras som:
$$
  \begin{aligned}
  Y_t = e_t + \theta_1 e_{t-1} + \theta_2 e_{t-2}
  \end{aligned}
$$

Likt en AR(2) process går det att visa hur autovariansen och autokorrelationen beräknas men det blir snabbt komplext och vi väljer här att visa enbart de resulterande autokorrelationerna:

$$
  \begin{aligned}
  \rho_1 &= \frac{\theta_1 + \theta_1\theta_2}{1 + \theta_1^2 + \theta_2^2} \\
  \rho_2 &= \frac{\theta_2}{1 + \theta_1^2 + \theta_2^2}\\
  \rho_k &= 0 \qquad \text{för } k > 2
  \end{aligned}
$$ {#eq-ar2-rho}

Vad detta betyder är att när $q = 2$ finner vi två nollskilda lagg och resterande är 0. Detta beteende går att utöka till den generella MA(q) processen där vi kan se nollskilda lagg när $k \le q$ och 0 för alla $k > q$.

## Partiell autokorrelation

Vi har tidigare i detta kapitel kunnat visa hur autokorrelationen beter sig för olika modeller, men i praktiken räcker det inte att undersöka den skattade autokorrelationen (SAC) för att enkelt identifiera en lämplig modell. Vi såg till exempel hur $\rho_k$ för AR(1) och AR(2) uppvisade samma långsamt avtagande mönster. Vi behöver därför introducera ett annat mått som kan hjälpa att välja en lämplig ordning på en AR-process, på samma sätt som autokorrelationen tydligt indikerar på en ordning av en MA-process.

Vi kan definiera den **partiella autokorrelationen** (eng. partial autocorrelation, PAC) som korrelationen mellan $Y_t$ och $Y_{t-k}$ när alla observationer emellan justerats bort. Vi definierar den enligt:

$$
  \begin{aligned}
  \phi_{kk} = cor(Y_t , Y_{t-k} | Y_{t-1}, Y_{t-2}, \dots, Y_{t-k+1})
  \end{aligned}
$$
givet att $Y_t$ kan anses normalfördelad. 

Detta är egentligen första gången ett sådant krav om normalfördelad $Y_t$ explicit uppkommer när vi har att göra med tidsserier så ett alternativt sätt att formulera PAC utan detta krav är:
$$
  \begin{aligned}
  \phi_{kk} = cor(&Y_t - \beta_1 Y_{t-1} - \beta_2 Y_{t-2} - \dots - \beta_{k-1} Y_{t-k+1}, \\
  &Y_{t-k} - \beta_1 Y_{t-k+1} - \beta_2 Y_{t-k+2} - \dots - \beta_{k-1} Y_{t-1})
  \end{aligned}
$$ {#eq-pacf}
där $\beta_1$ till $\beta_{k-1}$ är parametrar i en linjär prediktor som anpassats för att minimera MSPR till $Y_t$ och $Y_{t-k}$ respektive. PAC kan med denna formulering beskrivas som korrelationen mellan prediktionsfelet från de två tidpunkterna.

För enkelhetens skull anser vi $\phi_{11} = 1$ och kan visa att $\phi_{22}$ som:
$$
  \begin{aligned}
  \phi_{22} = \frac{\rho_2 - \rho_1^2}{1 - \rho_1^2}
  \end{aligned}
$$ {#eq-pacf22}

När vi använder @eq-pacf22 för en AR(1) modell fås:
$$
  \begin{aligned}
  \phi_{22} = \frac{\phi^2 - \phi^2}{1 - \phi^2} = 0
  \end{aligned}
$$
eftersom $\rho_k = \phi^k$. 

För en AR(2) fås via @eq-ar2-rho:
$$
  \begin{aligned}
  \phi_{22} &= \frac{ \left(\frac{\phi_1^2}{1 - \phi_2} + \phi_2\right)  - \left(\frac{\phi_1}{1 - \phi_2}\right)^2}{1 - \left(\frac{\phi_1}{1 - \phi_2}\right)^2}\\
  &= \frac{\frac{\phi_1^2}{1 - \phi_2} + \phi_2 - \frac{\phi_1^2}{(1 - \phi_2)^2}}{1 - \frac{\phi_1^2}{(1 - \phi_2)^2}} \\
  &= \frac{\frac{\phi_1^2 (1-\phi_2)}{(1-\phi_2)^2} - \frac{\phi_1^2}{(1 - \phi_2)^2} + \phi_2}{1 - \frac{\phi_1^2}{(1 - \phi_2)^2}}\\
  &= \frac{\frac{\phi_1^2}{(1-\phi_2)^2}(1 - \phi_2 - 1) + \phi_2}{1 - \frac{\phi_1^2}{(1 - \phi_2)^2}}\\
  &= \frac{\frac{\phi_1^2}{(1-\phi_2)^2}(- \phi_2) + \phi_2}{1 - \frac{\phi_1^2}{(1 - \phi_2)^2}}\\
  &= \frac{\phi_2 \left( 1 - \frac{\phi_1^2}{(1-\phi_2)^2}\right)}{1 - \frac{\phi_1^2}{(1 - \phi_2)^2}}\\
  &= \phi_2
  \end{aligned}
$$
det vill säga ytterligare ett lagg där den partiella autokorrelationen är nollskild. 

En generell regel för AR(p) är att för större lagg gäller $\phi_{kk} = 0$ när $k > p$. Detta innebär att vi får samma beteende i den partiella autokorrelationen för en AR-process som vi har i autokorrelationen för en MA-process; antalet nollskilda lagg motsvarar ordningen för processen.

Den partiella autokorrelationen kan också visas för en MA-process. För MA(1) gäller:

$$
  \begin{aligned}
  \phi_{22} = \frac{-\theta^2}{1 + \theta^2 + \theta^4}
  \end{aligned}
$$
och $\phi_{kk} = \frac{\theta^k(1 - \theta^2)}{1 - \theta^{2(k+1)}}$ för alla $k \ge 1$.

Den partiella autokorrelationen för en MA(1), och generellt för en MA(q), avtar långsamt med större $k$ vilket är samma fenomen som en AR(p)-process uppvisar för autokorrelationen. Vi har alltså två spegelvända beteenden för AR och MA för autokorrelationen och den partiella autokorrelationen. Vi kan sammanfatta dessa i följande tabell:

```{r}
#| echo: false
#| label: tbl-behavior-ac-pac

tibble(
  ` ` = c("Autokorrelation", "Partiell Autokorrelation"),
  `AR(p)` = c("Långsamt avtagande", "0 efter lagg p"),
  `MA(q)` = c("0 efter lagg q", "Långsamt avtagande")
) |>
  kable(
    caption = "Visuella beteenden hos autokorrelationer",
    align = "c"
  )

```

För enklare tidsserier kan denna tabell användas för att med hjälp av SAC och SPAC (eng. Sample Partial Autocorrelation) identifiera vilken typ av modell som är mest lämplig att använda. För mer komplicerade tidsserier kommer vi behöva ytterligare ett mått som introduceras i @sec-eacf.


## Referenser {.unnumbered}


