<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="sv-SE" xml:lang="sv-SE"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Logistisk regression – Statistisk teori och tillämpningar i R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../01-regression/11-other-link-functions.html" rel="next">
<link href="../01-regression/09-variable-selection.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Inget resultat",
    "search-matching-documents-text": "matchande dokument",
    "search-copy-link-title": "Kopiera länk för att söka",
    "search-hide-matches-text": "Göm ytterligare resultat",
    "search-more-match-text": "annat resultat i detta dokument",
    "search-more-matches-text": "fler resultat i detta dokument",
    "search-clear-button-title": "Rensa",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Avbryt",
    "search-submit-button-title": "Verkställ",
    "search-label": "Sök"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Statistisk teori och tillämpningar i R</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Skifta navigering" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../00-programming/00-basics-R.html" aria-current="page"> 
<span class="menu-text">Programmering i R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../01-regression/index.html"> 
<span class="menu-text">Regressionsanalys</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../02-variance/index.html"> 
<span class="menu-text">Varianssanalys</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Skifta sidonavigering" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../01-regression/index.html"><strong>DEL II - Regressionsanalys</strong></a></li><li class="breadcrumb-item"><a href="../01-regression/10-logistic-regression.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Logistisk regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Skifta sidonavigering" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Sök" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Sök"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inledning</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>DEL I - Programmering i R</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Skifta sektion">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../00-programming/00-basics-R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Grunderna i R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../00-programming/01-packages-and-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Paket och funktioner</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../00-programming/02-tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">tidyverse</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>DEL II - Regressionsanalys</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Skifta sektion">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Förord</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/00-intro-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduktion till regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/01-explorative-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Utforska samband</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/02-model-structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Modellanpassning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/03-model-assessment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modellutvärdering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/04-statistical-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Statistisk inferens</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/05-simultaneous-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Simultan inferens</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/06-complex-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Komplexa samband</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/07-multicollinearity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Multikollinearitet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/08-detailed-residuals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Detaljerad residualanalys</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/09-variable-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Modellvalidering och variabelselektion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/10-logistic-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Logistisk regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01-regression/11-other-link-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Andra länkfunktioner</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text"><strong>DEL III - Variansanalys</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Skifta sektion">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02-variance/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Förord</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02-variance/00-oneway-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Introduktion till variansanalys</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02-variance/01-random-factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Slumpmässiga faktorer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02-variance/02-control-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Kontrollvariabler</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Innehållsförteckning</h2>
   
  <ul>
  <li><a href="#binär-responsvariabel" id="toc-binär-responsvariabel" class="nav-link active" data-scroll-target="#binär-responsvariabel"><span class="header-section-number">11.1</span> Binär responsvariabel</a>
  <ul class="collapse">
  <li><a href="#logistiska-funktionen" id="toc-logistiska-funktionen" class="nav-link" data-scroll-target="#logistiska-funktionen"><span class="header-section-number">11.1.1</span> Logistiska funktionen</a></li>
  <li><a href="#logitlänken" id="toc-logitlänken" class="nav-link" data-scroll-target="#logitlänken"><span class="header-section-number">11.1.2</span> Logitlänken</a></li>
  </ul></li>
  <li><a href="#logistisk-regression" id="toc-logistisk-regression" class="nav-link" data-scroll-target="#logistisk-regression"><span class="header-section-number">11.2</span> Logistisk regression</a>
  <ul class="collapse">
  <li><a href="#glm" id="toc-glm" class="nav-link" data-scroll-target="#glm"><span class="header-section-number">11.2.1</span> <code>glm()</code></a></li>
  </ul></li>
  <li><a href="#utvärdering-av-logistisk-regression" id="toc-utvärdering-av-logistisk-regression" class="nav-link" data-scroll-target="#utvärdering-av-logistisk-regression"><span class="header-section-number">11.3</span> Utvärdering av logistisk regression</a></li>
  <li><a href="#funktion-för-utvärdering" id="toc-funktion-för-utvärdering" class="nav-link" data-scroll-target="#funktion-för-utvärdering"><span class="header-section-number">11.4</span> Funktion för utvärdering</a></li>
  <li><a href="#likelihoodkvottest" id="toc-likelihoodkvottest" class="nav-link" data-scroll-target="#likelihoodkvottest"><span class="header-section-number">11.5</span> Likelihoodkvottest</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../01-regression/index.html"><strong>DEL II - Regressionsanalys</strong></a></li><li class="breadcrumb-item"><a href="../01-regression/10-logistic-regression.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Logistisk regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Logistisk regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- New commands for matrices in regression -->
<!-- Creates a shortcommand for sums -->
<!-- CONTENT -->
<p>De tidigare kapitlen har fokuserat på modeller där responsvariabeln antas vara kvantitativ och kontinuerlig. Dessa modeller är begränsade till just detta fall men det går med enkla transformeringar att utöka modellerna att också anpassa modeller där responsvariabeln är en annan variabeltyp eller följer en annan skala. En utav dessa utökningar kallas för <em>logistisk regression</em> som modellerar en binär (två kategorier) kvalitativ responsvariabel.</p>
<p>Utöver att modellen anpassar en annan form av responsvariabel behöver vi också justera hur vi kommer fram till modellens anpassade värden. Inom linjär regression är minsta kvadratmetoden den absolut enklaste anpassningsmetoden med simpla formler för att skatta modellens parametrar, men även <em>maximum likelihoodmetoden</em> (ML) kan användas med hjälp av en <em>iterativ optimeringsalgoritm</em> för att finna de parameterskattningar som motsvarar minsta kvadratmetoden. Fördelen med att använda ML-metoder i modellanpassningen är att metoden kan användas för mer komplexa modeller, däribland logistisk regression.</p>
<section id="binär-responsvariabel" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="binär-responsvariabel"><span class="header-section-number">11.1</span> Binär responsvariabel</h2>
<p>Med en binär responsvariabel är det vanligast att vi kodar variabeln med 0 och 1, exempel: Om patienten tillfrisknade inom studieperioden så anger vi <span class="math inline">\(Y_i = 1\)</span> annars <span class="math inline">\(Y_i = 0\)</span>. Inom statistik och maskininlärning kallar vi problem där vi har en kvalitativ reponsvariabel för <em>klassificering</em> där målet är att skapa en modell som kan ge så många korrekta klassificeringar (predikterade klasser) som möjligt utan att <em>misklassificera</em> observationer till fel klasser.</p>
<p>Istället för att anta att <span class="math inline">\(Y|X \sim N(...)\)</span>, antar vi istället att <span class="math inline">\(Y|X \sim Bernoulli(...)\)</span>. Väntevärdet som modeller anpassar kommer inte längre direkt vara ett värde på responsvariabelns skala utan vi anser oss modellera <em>sannolikheten</em> att observationen antar värdet 1:</p>
<p><span class="math display">\[
\begin{aligned}
E[Y] = P(Y_i = 1) = \pi_i
\end{aligned}
\]</span> På samma sätt som vi använde medelvärdet av Y som en form av grundmodell för en kontinuerlig responsvariabel kan vi i detta fall använda andelen 1:or som en grundmodell för den binära responsvariabeln. Men vi vill även här skapa modeller som kan ta hänsyn till annan information, de förklarande variablerna, för att förhoppningsvis förbättra förklaringen av responsvariabeln.</p>
<p><span class="math display">\[
\begin{aligned}
E[Y|X] = P(Y_i = 1 | X_i)
\end{aligned}
\]</span></p>
<section id="logistiska-funktionen" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="logistiska-funktionen"><span class="header-section-number">11.1.1</span> Logistiska funktionen</h3>
<p>Eftersom linjära samband är lätta att arbeta med och tolka så vill vi formulera denna betingade sannolikhet utifrån den linjära modellen. En linjär regressionsmodell formuleras enligt:</p>
<p><span class="math display">\[
\begin{aligned}
\mathbf{Y} = \mathbf{X}\boldsymbol{\beta} + \mathbf{E}
\end{aligned}
\]</span> men vi kan också formulera enskilda <span class="math inline">\(Y_i\)</span> i matrisform enligt: <span class="math display">\[
\begin{aligned}
  Y_i = \mathbf{X}_i'\boldsymbol{\beta} + E_i
\end{aligned}
\]</span> där värden på <span class="math inline">\(Y_i\)</span> täcker hela den reella tallinjen (<span class="math inline">\(Y \in \mathbb{R}\)</span>). <span class="math inline">\(\mathbf{X}_i'\)</span> är den i:te raden från designmatrisen angiven som en kolumnvektor, därav behovet av att transponera till en radvektor.</p>
<p>En sannolikhet antar bara värden mellan 0 och 1, dvs. <span class="math inline">\(\pi \in [0,1]\)</span>, så vårt mål är att tvinga in den linjära regressionsmodellen från hela tallinjen till utfallsrummet <span class="math inline">\([0,1]\)</span>. Detta kan lösas med hjälp utav den <em>logistiska funktionen</em> som kan uttryckas på två olika sätt:</p>
<p><span class="math display">\[
\begin{aligned}
  P(Y_i = 1|Z_i) &amp;= \frac{exp[Z_i]}{1 + exp[Z_i]}\\
  \\
\text{alternativt}\\
\\
&amp;= \frac{1}{1 + exp[-Z_i]}
\end{aligned}
\]</span> där <span class="math inline">\(Z_i\)</span> är den anpassade linjära funktion som beror på de förklarande variablerna; <span class="math inline">\(\mathbf{X}_i'\boldsymbol{\beta}\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Notera
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notera att vi inte har någon felterm <span class="math inline">\(\mathbf{E}\)</span> här. Eftersom vi modellerar en sannolikhet för en viss händelse (<span class="math inline">\(Y_i = 1\)</span>), placeras felet eller slumpmässigheten med den logistiska funktionen i just den sannolikhetsdefinitionen.</p>
</div>
</div>
<p>Vi kan se hur den logistiska funktionen ser ut för olika värden på <span class="math inline">\(Z_i\)</span>.</p>
<div class="cell">
<details class="code-fold">
<summary>Visa kod</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">z =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="fl">0.01</span>),</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">exp</span>(z) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(z))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data) <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x =</span> z, <span class="at">y =</span> y) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"#d9230f"</span>) <span class="sc">+</span> </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"#d9230f"</span>) <span class="sc">+</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"P(Y = 1)"</span>, <span class="at">x =</span> <span class="st">"Z"</span>)</span></code><button title="Kopiera till urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-logistic-regression_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Formen på den logistiska funktionen.</figcaption>
</figure>
</div>
</div>
</div>
<p>Vi ser tydligt att värdena på <span class="math inline">\(P(Y_i = 1)\)</span> nu begränsas till värden mellan 0 och 1 där extremt negativa värden av <span class="math inline">\(Z_i\)</span> asymptotiskt går mot 0 och extremt positiva värden av <span class="math inline">\(Z_i\)</span> asymptotiskt går mot 1.</p>
<p>Med hjälp av den logistiska funktionen kan vi få ett uttryck för den logistiska regressionen ifall vi byter ut <span class="math inline">\(Z_i\)</span> med den linjära regressionsmodellen: <span class="math display">\[
\begin{aligned}
  P(Y_i = 1| \mathbf{X}_i, \boldsymbol{\beta}) = \frac{exp[\mathbf{X}_i'\boldsymbol{\beta}]}{1 + exp[\mathbf{X}_i'\boldsymbol{\beta}]}
\end{aligned}
\]</span></p>
<p>För en enkel logistisk regression innehållande en kontinuerlig förklarande variabel kan vi se följande effekter på den logistiska funktionens form givet olika parametervärden.</p>
<p>I den enkla logistiska regressionsmodellen (med en förklarande variabel) kan vi se hur olika parameterskattningar påverkar denna form. I följande kod skapar vi fem olika linjära modeller med olika värden på interceptet och lutningen.</p>
<div class="cell">
<details class="code-fold">
<summary>Visa kod</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Anger antalet observationer</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>nObs <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Skapar en egen logistisk funktion som transformerar värden</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>logisticFun <span class="ot">&lt;-</span> <span class="cf">function</span>(z){</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">exp</span>(z)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(z))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(p)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Skapar en variabel x</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">5</span>, <span class="dv">5</span>, <span class="at">length =</span> nObs),</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># En linjär funktion där beta0 är 0 och beta1 är 1</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">z1 =</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span>x,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># En linjär funktion med ett nollskilt värde på interceptet</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">z2 =</span> <span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">*</span>x,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># En linjär funktion med brantare lutning</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">z3 =</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">5</span><span class="sc">*</span>x,</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># En linjär funktion med ingen lutning</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">z4 =</span> <span class="dv">0</span> <span class="sc">+</span> <span class="dv">0</span><span class="sc">*</span>x,</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># En linjär funktion med negativ lutning</span></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">z5 =</span> <span class="dv">0</span> <span class="sc">-</span> <span class="dv">1</span><span class="sc">*</span>x</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Roterar materialet för enklare visualisering</span></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">-</span>x,</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"Modell"</span>, </span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"z"</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Skapar sannolikheten utifrån den logistiska funktionen</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">py =</span> <span class="fu">logisticFun</span>(z)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data) <span class="sc">+</span> <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> py) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span> </span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">rows =</span> <span class="fu">vars</span>(Modell)) <span class="sc">+</span> <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="dv">2</span>)</span></code><button title="Kopiera till urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-logistic-regression_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="384"></p>
<figcaption>Olika former på den logistiska funktionen givet olika värden på parametrar</figcaption>
</figure>
</div>
</div>
</div>
<p>Beroende på parametervärdena får denna så kallade sigmoidkurva (kurvan ser ut som ett S) olika former.</p>
<ul>
<li>z1: Med ett intercept på 0 hamnar punkten där kurvans sannolikhet är 0.5 vid värdet <span class="math inline">\(Z_i = 0\)</span>.</li>
<li>z2: När vi ändrar på <span class="math inline">\(\beta_0\)</span> flyttas också interceptet i den logistiska funktionen, ett positivt intercept innebär att kurvans sannolikhet är större än 0.5 vid värdet <span class="math inline">\(Z_i = 0\)</span>.</li>
<li>z3: När <span class="math inline">\(\beta_1\)</span> blir brantare blir också den logistiska funktionen brantare och vi hamnar snabbare ute i extremerna, 0 och 1.</li>
<li>z4: När <span class="math inline">\(\beta_1\)</span> är svag eller ligger nära 0 blir den logistiska funktionen mindre brant och vid 0 visas ingen förändring av sannolikheten. Vi kan jämföra detta med att i ett binärt fall vi har chansen att gissa rätt på 1 eller 0 hälften av tiden av ren slump. Om en variabel som vi lägger till i modellen inte bidrar med någon information, kvarstår denna rena gissning.</li>
<li>z5: En negativ <span class="math inline">\(\beta_1\)</span> innebär att sannolikheten blir mindre ju större värden på <span class="math inline">\(Z_i\)</span> vi har, vi vänder alltså på sigmoidkurvan.</li>
</ul>
</section>
<section id="logitlänken" class="level3" data-number="11.1.2">
<h3 data-number="11.1.2" class="anchored" data-anchor-id="logitlänken"><span class="header-section-number">11.1.2</span> Logitlänken</h3>
<p>Med hjälp av <em>länkfunktioner</em> kan vi plocka fram den linjära modellen från den logistiska funktionen och andra varianter av funktioner som bygger vidare på den linjära modellen. Generellt kan vi säga att en länkfunktion är den transformering som sker från den linjära modellen till den modell som beskriver den icke-kontinuerliga responsvariabeln.</p>
<p>För logistisk regression används <em>logitlänken</em>: <span class="math display">\[
\begin{aligned}
  log\left( \frac{\pi_i}{1 - \pi_i}\right) = Z_i = \mathbf{X}_i'\boldsymbol{\beta}
\end{aligned}
\]</span></p>
<p>I denna litteratur betecknar <span class="math inline">\(log()\)</span> alltid den naturliga logaritmen<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Vi kan uttrycka det som att den logistiska regresionssmodellen är linjär i sin logitlänk för sannolikheten <span class="math inline">\(\pi\)</span>.</p>
<p>Denna länk visar också hur vi bör tolka parametrar från den linjära modellen. Uttrycket inuti logaritmen beskriver ett <em>odds</em>, sannolikheten att något inträffar dividerat med sannolikheten att något inte inträffar, specifikt oddset att <span class="math inline">\(Y_i = 1\)</span>. Den linjära modellen beskriver då <em>logodds</em> och en lutningsparameter beskriver en förändring i logodds, även kallad en <em>oddskvot</em>, som vi kommer återkomma till senare.</p>
</section>
</section>
<section id="logistisk-regression" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="logistisk-regression"><span class="header-section-number">11.2</span> Logistisk regression</h2>
<p>Till skillnad från vanlig linjär regression kan vi inte längre använda minsta kvadratmetoden för att skatta modellens parametrar då vi inte längre har en linjär relation mellan de förklarande och responsvariabeln. Istället behöver vi använda responsvariabelns (log)likelihoodfunktion och iterativt optimera för att hitta de parametervärden som genererar det högsta värdet på funktionen.</p>
<!-- TODO EXPLAIN MORE ABOUT LIKELIHOOD FUNCTIONS -->
<p>För en Bernoulli-fördelad slumpvariabel kan vi skriva loglikelihoodfunktionen som: <span class="math display">\[
\begin{aligned}
logL(\pi) &amp;= log\left[\prod\limits_{i = 1}^n \left( \pi^{Y_i} \cdot (1 - \pi)^{1 - Y_i}\right) \right]
\\&amp;= \sum\limits_{i = 1}^{n_1}log(\pi) + \sum\limits_{i = n_1 + 1}^{n}log(1 - \pi)
\end{aligned}
\]</span></p>
<p>där <span class="math inline">\(\pi\)</span> är sannolikheten för <span class="math inline">\(P(Y=1)\)</span>, <span class="math inline">\(n\)</span> är antalet observationer och <span class="math inline">\(n_1\)</span> är antalet 1:or i materialet<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. När vi modellerar den Bernoullifördelade variabeln med en logistisk regression antar vi att <span class="math inline">\(P(Y=1)\)</span> varierar beroende på värden av våra förklarande variabler, så vi byter ut <span class="math inline">\(\pi\)</span> med ett uttryck som förhåller sig till de förklarande variablerna och <span class="math inline">\(\beta\)</span>. Detta ger loglikelihoodfunktionen: <span class="math display">\[
\begin{aligned}
logL(\boldsymbol{\beta}) = \sum_{i = n_1 + 1}^{n} \operatorname{-}\mathbf{X}_i'\boldsymbol{\beta} - \sum_{i=1}^n \ln (1 + exp\left[\operatorname{-}\mathbf{X}_i'\boldsymbol{\beta} \right])
\end{aligned}
\]</span> Denna funktion optimeras numeriskt, vanligtvis med Fisher Scoring Algorithm<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Det är denna algoritm som R använder sig utav när vi en logistisk regressionsmodell anpassas.</p>
<section id="glm" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="glm"><span class="header-section-number">11.2.1</span> <code>glm()</code></h3>
<p><code>glm()</code> används för att anpassa <em>generaliserade</em> linjära modeller, en mer flexibel typ av linjära modeller. Med hjälp av argumentet <code>family</code> kan vi ange vilken fördelning och länkfunktion som vi anser responsvariabeln behöver för att transformera den linjära modellen till den aktuella modellen för responsvariabeln.</p>
<p>Objektet som <code>glm()</code> returnerna har många liknande delobjekt som <code>lm()</code>. Det går även att använda liknande funktioner såsom <code>summary()</code>, <code>coef()</code>, och <code>residuals()</code> för att plocka ut enskilda objekt som vi är vana vid att göra. Däremot kommer dessa objekt inte tolkas på samma sätt som vi har gjort i tidigare kapitel då vi måste ta hänsyn till den förändrade modellstrukturen.</p>
<p>Vi kan anpassa en modell baserat på <code>mtcars</code> där vi modellerar huruvida bilen har automat eller manuell växel <code>am</code>. I datamaterialet har variabeln redan kodats binärt där 0 är automatisk och 1 manuell växling. Vi använder tre variabler ur data för att modellera denna responsvariabel.</p>
<div class="cell">
<details class="code-fold">
<summary>Visa kod</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Anpassar modellen</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glm</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    am <span class="sc">~</span> mpg <span class="sc">+</span> cyl <span class="sc">+</span> hp,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> mtcars,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Anger binomial som familj där logitlänken är länkfunktionen</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="st">"binomial"</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Sammanfattar modellen</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Kopiera till urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = am ~ mpg + cyl + hp, family = "binomial", data = mtcars)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept) -27.66400   16.22158  -1.705   0.0881 .
mpg           1.09425    0.58578   1.868   0.0618 .
cyl          -0.63106    0.68703  -0.919   0.3583  
hp            0.06299    0.03046   2.068   0.0386 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 43.230  on 31  degrees of freedom
Residual deviance: 18.347  on 28  degrees of freedom
AIC: 26.347

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>I summary-utskriften får vi nu annan information än vad vi är vana vid. Koefficienttabellen finns fortfarande kvar med lite andra rubriker, men sedan saknas en modellutvärdering som vi är van att se. Istället presenteras modellens <em>devians</em>, ett tillhörande AIC-värde och ett resultat från optimeringsalgoritmen. I och med att vi nu genomför optimering måste vi kontrollera att optimeringen faktiskt har <em>konvergerat</em>, det vill säga nått sitt maximum, vilket innebär att vi behöver vara uppmärksamma på fel- eller varningsmeddelanden som R ger oss relaterat till konvergensen. I detta fall funkade allting utan problem och optimeringen har konvergerat efter 7 iterationer.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Viktigt
</div>
</div>
<div class="callout-body-container callout-body">
<p>Om en modell inte konvergerar kan vi öka antalet iterationer vi tillåter optimeringsalgoritmen att gå innan den stannar. Vi behöver då lägga till <code>glm(..., control = list(maxit = 50))</code> eller något annat större värde. Standardargumentet är att algoritmen genomför 25 iterationer.</p>
</div>
</div>
<p>Tänk på att en utskrift direkt från R för denna modell inte är lämpligt att använda i presentationssyften utan vi behöver återigen plocka ut de olika delarna och skapa snyggare tabeller.</p>
<div class="cell">
<details class="code-fold">
<summary>Visa kod</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model) <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>, <span class="at">caption =</span> <span class="st">"Modellens skattade koefficienter."</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Variabel"</span>, <span class="st">"Skattning"</span>, <span class="st">"Medelfel"</span>, <span class="st">"z-värde"</span>, <span class="st">"p-värde"</span>))</span></code><button title="Kopiera till urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Modellens skattade koefficienter.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variabel</th>
<th style="text-align: right;">Skattning</th>
<th style="text-align: right;">Medelfel</th>
<th style="text-align: right;">z-värde</th>
<th style="text-align: right;">p-värde</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-27.664</td>
<td style="text-align: right;">16.222</td>
<td style="text-align: right;">-1.705</td>
<td style="text-align: right;">0.088</td>
</tr>
<tr class="even">
<td style="text-align: left;">mpg</td>
<td style="text-align: right;">1.094</td>
<td style="text-align: right;">0.586</td>
<td style="text-align: right;">1.868</td>
<td style="text-align: right;">0.062</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cyl</td>
<td style="text-align: right;">-0.631</td>
<td style="text-align: right;">0.687</td>
<td style="text-align: right;">-0.919</td>
<td style="text-align: right;">0.358</td>
</tr>
<tr class="even">
<td style="text-align: left;">hp</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">2.068</td>
<td style="text-align: right;">0.039</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="lutningskoefficienter" class="level4" data-number="11.2.1.1">
<h4 data-number="11.2.1.1" class="anchored" data-anchor-id="lutningskoefficienter"><span class="header-section-number">11.2.1.1</span> Lutningskoefficienter</h4>
<p>Koefficienttabellens lutningsparametrar tolkas <strong>inte</strong> som i en vanlig linjär regression eftersom länkfunktionen transformerar den linjära modellen till responsvariabelns skala, till exempel när antalet miles per gallon (<code>mpg</code>) ökar med ett ökar <strong>inte</strong> y med 1.094. Istället beskriver dessa parametrar, <span class="math inline">\(\beta_j\)</span>, förändringen i logoddset för <span class="math inline">\(Y = 1\)</span> och kan efter en transformering, <span class="math inline">\(e^{\beta_j}\)</span>, beskriva oddskvoten för <span class="math inline">\(Y=1\)</span> när den förklarande variabeln ökar med en enhet.</p>
<p>För just denna modell kan vi transformera parameterskattningen för <code>mpg</code> enligt <span class="math inline">\(e^{1.094} = 2.987\)</span> som att när <code>mpg</code> ökar med en enhet, så är oddset att motorn är manuellt växlad (<span class="math inline">\(Y = 1\)</span>) ca 3 gånger högre.</p>
<p>Matematiskt kan vi skriva upp detta likt: <span class="math display">\[
\begin{aligned}
  \hat{\beta}_1 &amp;= \frac{p(y = 1|x = 1)}{p(y = 1|x = 0)} = \frac{log(\frac{\pi_{x = 1}}{1 - \pi_{x = 1}})}
    {log(\frac{\pi_{x = 0}}{1 - \pi_{x = 0}})}\\
    \\
    e^{\hat{\beta}_1} &amp;= \frac{\frac{\pi_{x = 1}}{1 - \pi_{x = 1}}}
    {\frac{\pi_{x = 0}}{1 - \pi_{x = 0}}} \Rightarrow \\
    \hat{OR}_{1 vs 0} &amp;= \frac{Odds(y = 1|x = 1)}{Odds(y = 1|x = 0)}
\end{aligned}
\]</span></p>
</section>
<section id="inferens" class="level4" data-number="11.2.1.2">
<h4 data-number="11.2.1.2" class="anchored" data-anchor-id="inferens"><span class="header-section-number">11.2.1.2</span> Inferens</h4>
<p>Givet att en lämplig likelihoodfunktion används och ‘nog stort data’ anses testvariabeln <span class="math inline">\(\left(Z = \frac{\hat{\beta}_j - \beta_j}{SE_{\hat{\beta}_j}}\right)\)</span> följa en standardiserad normalfördelning. Detta kallas för ett <em>Wald-test</em> och är de tester som vi ser i koefficienttabellen.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> Medelfelen för respektive parametrar tas från kovariansmatrisen för <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> som beräknas genom att använda andraderivator från likelihoodfunktionen vilket medför att vi kan skapa tester och intervallskattningar för <span class="math inline">\(\boldsymbol{\beta}\)</span>.</p>
</section>
</section>
</section>
<section id="utvärdering-av-logistisk-regression" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="utvärdering-av-logistisk-regression"><span class="header-section-number">11.3</span> Utvärdering av logistisk regression</h2>
<p>I vanlig regression kan vi utvärdera modellens lämplighet genom residualanalys där vi jämför <span class="math inline">\(Y_i - \hat{Y}_i\)</span> och undersöker om residualerna uppfyller modellantaganden. I logistisk regression kommer den observerade responsvariabeln bara anta två värden, 1 och 0, och modellens anpassade värden anta värden mellan 0 och 1 vilket innebär att vanliga residualer inte längre jämför samma sorts variabel.</p>
<p>I ett klassificeringsproblem kan vi istället jämföra de observerade klasserna för <span class="math inline">\(Y\)</span> med predikterade klasser <span class="math inline">\(\hat{Y}\)</span> i en korstabell, även kallad <em>förväxlingsmatris</em>. Eftersom modellen egentligen predikterar en sannolikhet för <span class="math inline">\(Y = 1\)</span> och inte den faktiska klassen behöver vi gå ett steg längre för att faktiskt kunna skapa förväxlingsmatrisen. Vi kan tänka att sannolikheter större än 0.5 innebär att <span class="math inline">\(Y = 1\)</span> är mer sannolikt att inträffa än <span class="math inline">\(Y = 0\)</span> vilket leder oss till att också prediktera den klassen för dessa observationer, <span class="math inline">\(\hat{Y} = 1\)</span>.</p>
<p>När vi skapar förväxlingsmatrisen räknar räknar frekvenserna av antalet <span class="math inline">\(Y = 1\)</span> som blivit predikterade till de olika klasserna <span class="math inline">\(\hat{Y} = 1\)</span> (<span class="math inline">\(f_{11}\)</span>) och <span class="math inline">\(\hat{Y} = 0\)</span> (<span class="math inline">\(f_{10}\)</span>) och antalet <span class="math inline">\(Y = 0\)</span> som blivit predikterade till respektive klass (<span class="math inline">\(f_{01}\)</span> och <span class="math inline">\(f_{00}\)</span>).</p>
<table style="border-collapse: collapse; width: 50%;">
<caption>
Förväxlingsmatris med frekvenser av olika fall.
</caption>
<thead>
<tr>
<th colspan="2">
</th>
<th colspan="2" style="text-align: center;">
Predikterad klass
</th>
</tr>
<tr>
<th colspan="2">
</th>
<th style="border: 1px solid black; padding: 5px;">
<span class="math inline">\(\hat{Y} = 1\)</span>
</th>
<th style="border: 1px solid black; padding: 5px;">
<span class="math inline">\(\hat{Y} = 0\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td rowspan="2" style="padding-right: 15px; font-weight: bold;">
Sann klass
</td>
<td style="border: 1px solid black; padding: 5px;">
<span class="math inline">\(Y = 1\)</span>
</td>
<td style="border: 1px solid black; padding: 5px; background-color: #D1FFBD;">
<span class="math inline">\(f_{11}\)</span>
</td>
<td style="border: 1px solid black; padding: 5px;">
<span class="math inline">\(f_{10}\)</span>
</td>
</tr>
<tr>
<td style="border: 1px solid black; padding: 5px;">
<span class="math inline">\(Y = 0\)</span>
</td>
<td style="border: 1px solid black; padding: 5px;">
<span class="math inline">\(f_{01}\)</span>
</td>
<td style="border: 1px solid black; padding: 5px; background-color: #D1FFBD;">
<span class="math inline">\(f_{00}\)</span>
</td>
</tr>
</tbody>
</table>
<p>I R kan en sådan tabell enkelt fås fram genom <code>table(y, yHat)</code> där <code>y</code> innehåller de sanna värdena och <code>yHat</code> innehåller prediktionerna. Notera att dessa vektorer måste ha samma observationsordning för att korstabellen ska blir korrekt. Utifrån förväxlingsmatrisen kan ett antal utvärderingsmått beräknas som fokuserar på olika aspekter av modellens prestanda.</p>
<p>De två enklaste måtten är andelen korrekta prediktioner och andelen felaktiga prediktioner. Vi kallar andelen korrekta prediktioner för modellens <em>träffsäkerhet</em> (eng. Accuracy) och andelen felaktiga prediktioner för modellens <em>felkvot</em> (eng. Misclassification rate).</p>
<p><span class="math display">\[
\begin{aligned}
  \text{Träffsäkerhet} &amp;= \frac{f_{11} + f_{00}}{n} = \frac{f_{11} + f_{00}}{f_{11} + f_{10} + f_{01} + f_{00}} \\
  \text{Felkvot} &amp;= \frac{f_{10} + f_{01}}{n} = \frac{f_{10} + f_{01}}{f_{11} + f_{10} + f_{01} + f_{00}} = 1 - \text{Träffsäkerhet} \\
\end{aligned}
\]</span> När träffsäkerheten i modellen är hög kommer felkvoten vara låg och vice versa vilket gör att endast ett av dessa mått egentligen behöver beräknas. Problemet med att bara använda dessa mått som en indikation på modellens prestanda är att de lätt kan missa att modellen fokuserar sin anpassning på att prediktera en av klasserna bra. När vi arbetar med klassificering så spelar andelen av vår data som tillhör vardera klass roll, detta kallas för <em>klassbalanser</em>. När vi ska modellera en binär responsvariabel är det bra att först ta fram en tabell med andelen som tillhör klass 1 och andelen som tillhör klass 0 för att bilda en uppfattning om vilken och hur mycket information vi har om de båda.</p>
<p>Om andelarna är balanserade, det vill säga nära 50% för de båda andelarna, kommer modellen ha lika mycket information om de båda klasserna och kan förmodligen anpassa en modell som tar hänsyn till att vi vill prediktera båda klasserna rätt. Om andelarna däremot är olika stora kommer problemet att modellera <span class="math inline">\(P(Y = 1)\)</span> bli svårare, och svårighetsgraden avgörs av hur stor skillnad det är mellan andelarna. Om det är stor skillnad på andelarna säger vi att vi har <em>obalanserade klasser</em> vilket leder till svårigheter att hitta en bra och meningsfull modell. Exempelvis om vi har 95% 0:or och 5% 1:or kanske modellen tycker att den bästa prediktionen vi kan göra är att säga att alla observationer är 0, för då blir träffsäkerheten 95%.</p>
<p>Vi behöver därför titta på flera mått för att avgöra om modellen är överlag bra eller kanske bara fokuserar på att modellera den ena av klasserna. Med fokus på <span class="math inline">\(Y = 1\)</span> beskriver <em>sensitiviteten</em> (eng. True Positive Rate, sensitivity, recall) hur stor andel av de observerade 1:orna som faktiskt också predikterades som 1:or. Motsatsen är <em>specificiteten</em> (eng. True Negative Rate, specificity) som beskriver hur stor andel obsrverade icke-1:or som också predikterades som icke-1:or.</p>
<p><span class="math display">\[
\begin{aligned}
\text{Sensitivitet} &amp;= \frac{f_{11}}{f_{11} + f_{10}}\\
\text{Specificitet} &amp;= \frac{f_{00}}{f_{01} + f_{00}}
\end{aligned}
\]</span> Om det ena måttet är stort och det andra litet betyder det att modellen fokusera på endast någon av klasserna, medan om båda måtten är stora betyder det att modellen lyckats prediktera alla klasser lika bra.</p>
<p>Hur stora klassobalanser som är hanterbart avgörs dels av hur starkt sambandet mellan våra förklarande variabler och <span class="math inline">\(Y\)</span> är, och dels av det totala antalet observationer som finns i data. Har vi ett starkt samband mellan våra förklarande variabler och <span class="math inline">\(Y\)</span> så kan vi ha mer obalanserade klasser eftersom variablerna kan på ett bra sätt separera dem. På samma sätt, om vi har väldigt många observationer så kan vi ha mer obalanserade klasser då det ändå finns mycket information som modellen kan använda för att hitta en bra anpassning. Det är bra att beräkna sensitivitet och specificitet på tränings- och valideringsmängden för att få en förståelse för om man har problem med obalanserade klasser eller ej. Har vi problem med obalanserade klasser finns det olika metoder för det som kan användas i vissa fall, men som ligger utanför detta underlag.</p>
</section>
<section id="funktion-för-utvärdering" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="funktion-för-utvärdering"><span class="header-section-number">11.4</span> Funktion för utvärdering</h2>
<p>Vi kan skapa en funktion i R som sammanställer denna korstabell och utvärderingsmått åt oss:</p>
<div class="cell">
<details class="code-fold">
<summary>Visa kod</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Funktion som skapar förväxlingsmatris med tillhörande mått för klassificeringsproblem</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># newData  : Materialet innehållande förklarande variabler </span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># model    : Den skattade modellen</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># trueY    : Vektor innehållande de sanna klass-värden i samma ordning som observationerna i newData</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>classEvaluation <span class="ot">&lt;-</span> <span class="cf">function</span>(newData, model, trueY, <span class="at">type =</span> <span class="st">"class"</span>, <span class="at">digits =</span> <span class="dv">3</span>){</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Predikterar klassen för newData givet den skattade modellen med gränsen 0.5</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  pred <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">predict</span>(model, <span class="at">newdata =</span> newData, <span class="at">type =</span> <span class="st">"response"</span>) <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Konverterar de predikterade klasserna till en faktor med samma nivåer som de sanna </span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># klasserna</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  pred <span class="ot">&lt;-</span> <span class="fu">factor</span>(pred, <span class="at">levels =</span> <span class="fu">levels</span>(<span class="fu">factor</span>(trueY)))</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Skapar förväxlingsmatris med rader som indikerar sanna klassen och kolumnen som</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># indikerar predikterade klassen</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  confusion <span class="ot">&lt;-</span> <span class="fu">table</span>(trueY, pred)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Träffsäkerhet är antalet korrekta prediktioner dividerat med antalet observationer</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  accuracy <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(confusion)) <span class="sc">/</span> <span class="fu">sum</span>(confusion)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Felkvoten är 1 - träffsäkerheten</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>  misclass <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> accuracy</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Sensitivitet är antalet korrekta prediktioner AV DEN NUVARANDE KLASSEN dividerat </span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># med antalet observationer AV DEN NUVARANDE KLASSEN</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  sensitivity <span class="ot">&lt;-</span> <span class="fu">diag</span>(confusion) <span class="sc">/</span> <span class="fu">rowSums</span>(confusion) </span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Specificitet är antalet korrekta prediktioner AV ICKE DEN NUVARANDE KLASSEN dividerat </span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># med antalet observationer AV ICKE DEN NUVARANDE KLASSEN</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>  specificity <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(confusion)){</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>    specificity[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(confusion[<span class="sc">-</span>i, <span class="sc">-</span>i])<span class="sc">/</span><span class="fu">sum</span>(confusion[<span class="sc">-</span>i, ])</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Sammanställer alla resultat i en egen lista som sedan returneras</span></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>  evaluation <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">confusionMatrix =</span> confusion, </span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>                     <span class="at">overall =</span> </span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">cbind</span>(träffsäkerhet <span class="ot">=</span> accuracy, </span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>                             <span class="at">felkvot =</span> misclass),</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>                     <span class="at">classWise =</span> </span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">rbind</span>(<span class="at">sensitivitet =</span> sensitivity,</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>                             <span class="at">specificitet =</span> specificity)</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(evaluation)</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Kopiera till urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Med hjälp av den skapade funktionen kan vi utvärdera modellen som anpassats på <code>mtcars</code>. Nu har vi endast en träningsmängd vilket innebär att utvärderingen endast kommer visa hur bra modellen är på det data den använt i sin anpassning, men ifall vi hade en valideringsmängd hade vi med funktionen kunnat lägga in valideringsmängdens data och responsvariabel i <code>newData</code> och <code>trueY</code> som också ger oss samma mått vilka vi kan använda för att bedöma modellens generaliserbarhet.</p>
<div class="cell">
<details class="code-fold">
<summary>Visa kod</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>evaluation <span class="ot">&lt;-</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">classEvaluation</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">newData =</span> mtcars <span class="sc">%&gt;%</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        mpg, cyl, hp</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>      ),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">model =</span> model,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">trueY =</span> mtcars<span class="sc">$</span>am</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>evaluation<span class="sc">$</span>confusionMatrix <span class="sc">%&gt;%</span> </span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Modellens förväxlingsmatris"</span>)</span></code><button title="Kopiera till urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Modellens förväxlingsmatris</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">11</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Visa kod</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>evaluation<span class="sc">$</span>overall <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Modellens övergripande mått"</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Träffsäkerhet"</span>, <span class="st">"Felkvot"</span>), <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Kopiera till urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Modellens övergripande mått</caption>
<thead>
<tr class="header">
<th style="text-align: right;">Träffsäkerhet</th>
<th style="text-align: right;">Felkvot</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.875</td>
<td style="text-align: right;">0.125</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Visa kod</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>evaluation<span class="sc">$</span>classWise <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Modellens klasspecifika mått"</span>, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Kopiera till urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Modellens klasspecifika mått</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">0</th>
<th style="text-align: right;">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sensitivitet</td>
<td style="text-align: right;">0.895</td>
<td style="text-align: right;">0.846</td>
</tr>
<tr class="even">
<td style="text-align: left;">specificitet</td>
<td style="text-align: right;">0.846</td>
<td style="text-align: right;">0.895</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>I förväxlingsmatrisen ser vi att vi fått majoriteten av observationerna i diagonalen, det vill säga korrekta prediktioner. Träffsäkerheten är 87.5% vilket är högt, men det är fortfarande ett antal observationer som predikterats fel. Det är dock betydligt bättre än att slumpmässigt gissa sig till klassen (50%) vilket indikerar på att modellens förklarande variabler faktiskt bidrar till responsvariabeln. De klasspecifika måtten är jämna, 85-90% för respektive vilket antyder att modellen är lika bra på att prediktera klass 1 som den är att prediktera klass 0.</p>
<p>Om vi har dålig anpassning på träningsdata så har vi troligen valt en felaktig eller för enkel modell till exempel att vi inte har med rätt förklarande variabler i modellen. Det kan också vara så att det finns en stor grad av slumpmässighet i vår responsvariabel, det vill säga att vi har mycket brus i data, vilket kan göra att det är svårt att hitta en bra modell. Vi kan tänka oss ett scenario där <span class="math inline">\(\pi_i\)</span> alltid ligger runt 0.5, oavsett värden på alla potentiella förklarande variabler vilket leder till att vår modell inte kan bli bättre än slumpmässig gissning av klasserna 0 och 1.</p>
<p>Om våra utvärderingsmått är allmänt dåliga så är det inte relevant att göra vidare analyser med modellen, t.ex. undersöka vilka variabler som är signifikanta. Detta gäller speciellt om sensitivitet eller specificitet är nära noll på träningsdata. Då har vi klassificerat alla (eller nästan alla) observationer till endast en klass, och vår modell har inte förmågan att särskilja de två klasserna i responsvariabeln.</p>
</section>
<section id="likelihoodkvottest" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="likelihoodkvottest"><span class="header-section-number">11.5</span> Likelihoodkvottest</h2>
<p>Ytterligare en metod vi kan använda att utvärdera modeller, utöver förväxlingsmatrisen och dess mått eller AIC, är modellens likelihood. Likt när vi jämför den förklarande variationen mellan modeller i linjär regression kan vi anse en skillnad i likelihood beskriva hur mycket en eller flera variabler tillför till modellen, och likt ett partiellt F-test kan vi genomföra inferens på denna skillnad i likelihood.</p>
<p>Hypoteserna som undersöks formuleras på samma sätt som i ett partiellt F-test, i <span class="math inline">\(H_0\)</span> anges de alla lika med 0 och mothypotesen är att minst en av parametrarna är signifikant skild från 0. Vi kan därefter definiera en komplett och reducerad modell som båda har ett tillhörande likelihood-värde, alltså hur troligt modellens parametrar har genererat det observerade data. Om vi sedan jämför dessa två likelihood får vi en bedömning av hur stor skillnaden är i relation till den kompletta modellens värde, därav namnet <em>likelihoodkvottest</em> (eng. Likelihood ratio test).</p>
<p><span class="math display">\[
\begin{aligned}
  LR_{test} = -2 \ln \left(\frac{L_R}{L_F}\right) = -2 \ln L_R - (-2 \ln L_F)
\end{aligned}
\]</span> där <span class="math inline">\(L_R\)</span> och <span class="math inline">\(L_F\)</span> kommer från den reducerade respektive kompletta modellen.</p>
<p>I R kan vi ta ut loglikelihooden från en anpassad modell med funktionen <code>logLik()</code> vilket skulle motsvara <span class="math inline">\(\ln(L_R)\)</span> och <span class="math inline">\(\ln(L_F)\)</span> i formeln. Statistikan anses vara <span class="math inline">\(\chi^2\)</span>-fördelad med ‘antalet parametrar som undersöks’ frihetsgrader.</p>
<div class="cell">
<details class="code-fold">
<summary>Visa kod</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># En reducerad modell med två färre variabler</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(am <span class="sc">~</span> mpg, <span class="at">data =</span> mtcars, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Beräkning av teststatistikan, c() används för att endast plocka ut värdet av statistikan inte andra termer från logLik()</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>LR <span class="ot">&lt;-</span> (<span class="sc">-</span><span class="dv">2</span><span class="sc">*</span><span class="fu">logLik</span>(model2) <span class="sc">-</span> (<span class="sc">-</span><span class="dv">2</span><span class="sc">*</span><span class="fu">logLik</span>(model))) <span class="sc">%&gt;%</span> <span class="fu">c</span>()</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Beräkning av p-värdet</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>pValue <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(<span class="at">q =</span> LR, <span class="at">df =</span> <span class="dv">2</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code><button title="Kopiera till urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>P-värdet för testet är 0.0035 vilket är mindre än en signifikansnivå på 5 procent och medför att vi kan förkasta <span class="math inline">\(H_0\)</span>. De två variabler som undersöks har minst en som bidrar med en signifikant effekt på responsvariabeln.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Detta gäller också för litteratur om regression och statistik i allmänhet. I de mer ovanliga fall när logaritmer med andra baser används brukar det anges explicit, ex. <span class="math inline">\(log_2(x)\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Vi antar att vi summerar uttrycket först över alla 1:or med tillhörande sannolikhet <span class="math inline">\(\pi\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>En algoritm som använder andraderivator för att succestivt hitta bättre värden för <span class="math inline">\(\boldsymbol{\beta}\)</span>. För mer detaljer, se .<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Vi kan också använda att <span class="math inline">\(Z^2 \approx \chi^2_{df = 1}\)</span> om <span class="math inline">\(n\)</span> är stor.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopierat!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopierat!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../01-regression/09-variable-selection.html" class="pagination-link" aria-label="Modellvalidering och variabelselektion">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Modellvalidering och variabelselektion</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../01-regression/11-other-link-functions.html" class="pagination-link" aria-label="Andra länkfunktioner">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Andra länkfunktioner</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>