---
engine: knitr
filters: 
  - webr
  - diagram
---
<!-- CONTENT -->

# Neurala nätverk {#sec-neural-networks}

**Neurala nätverk** förekommer i många olika former i samhället och vi termen kan användas för att beskriva lite vad som helst. I detta underlag beskriver neurala nätverk komplexa modeller som med hjälp av ........

Det finns *väldigt många* olika sorters nätverk, en översikt kan hittas [här](https://www.asimovinstitute.org/neural-network-zoo/). Alla dessa nätverk kan användas för att lösa många olika problem, till exempel supervised learning eller mer avancerade problem som reinforcement learning. 

För supervised learning kan vi använda **feed-forward** nätverk, såsom Multi Layer Perceptron (MLP), där informationen endast går åt ett håll i nätverket. På samma sätt som för trädmodeller börjar vi med att visa en övergripande struktur för att definiera några termer som kommer användas frekvent.


::: {#fig-nn-structure}
```{.tikz}
\definecolor{myOrange}{RGB}{255,153,0}
\definecolor{myBlue}{RGB}{16,152,247}
\usetikzlibrary{positioning}
\usetikzlibrary{arrows.meta}

\begin{tikzpicture}[
  block/.style={draw, rectangle, minimum width=1.6cm, minimum height=1cm, fill=myBlue!60, font=\Large},
  input/.style={draw, circle, minimum width=1.6cm, minimum height=1.6cm, fill=myOrange!60, font=\Large},
  output/.style={draw, circle, minimum width=1.6cm, minimum height=1.6cm, fill=myOrange!30, font=\Large},
  node distance=2cm and 3cm,
  >=Stealth
]

% Nodes
\node[input] (in1) {$x_1$};
\node[input, right=1cm of in1] (in2) {$x_2$};
\node[input, right=1cm of in2] (in3) {...};
\node[input, right=1cm of in3] (in4) {$x_p$};

\node[block, below=1.5cm of in1] (hid1) {$z_1$};
\node[block, right=1cm of hid1] (hid2) {$z_2$};
\node[block, right=1cm of hid2] (hid3) {...};
\node[block, right=1cm of hid3] (hid4) {$z_M$};

\node[output, below=1.5cm of hid1] (out1) {$f_1$};
\node[output, right=1cm of out1] (out2) {$f_2$};
\node[output, right=1cm of out2] (out3) {...};
\node[output, right=1cm of out3] (out4) {$f_K$};

% Edges
% Fully connect input -> hidden
\foreach \i in {1,...,4} {
    \foreach \j in {1,...,4} {
        \draw[->, thick] (in\i) -- (hid\j);
    }
}

% Fully connect hidden -> output
\foreach \i in {1,...,4} {
    \foreach \j in {1,...,4} {
        \draw[->, thick] (hid\i) -- (out\j);
    }
}

\end{tikzpicture}
```
Ett exempel på ett neuralt nätverk
:::

I @fig-nn-structure innehåller **neuroner** uppdelat i tre lager; **inputlagret** bestående av $p$ förklarande variabler ($x_1 - x_p$), ett **gömt lager** bestående av $M$ linjärkombinationer ($z_1 - z_M$), och ett **outputlager** bestående av $K$ klassprediktioner för klassificering eller $K$ neuroner för de parametrar som ska predikteras för regression (vanligtvis en). Figuren visar också hur informationen flödar genom enkelriktade pilar från inputlagret, till det gömda lagret och till sist till outputlagret. Ett feed-forward nätverk kan bestå av ett eller flera gömda lager där kopplingar endast sker mellan neuroner i efterföljande lager, inte inom lagren.

Inom "vanlig" regression kan vi transformera de förklarande variablerna för att lyckas modellera mer icke-linjära samband. Det är dock svårt att veta exakt vilken transformation som behövs för att lösa varje problem och det blir nästintill omöjligt att hantera komplexa datastrukturer såsom text eller bilder. Detta kallas för **feature engineering** inom maskininlärning. 

Syftet med neurala nätverkets gömda lager är att automatiskt lära sig lämpliga transformationer av de förklarande variablerna för att lyckas identifiera icke-linjära samband som sedan transformeras linjärt i det sista outputlagret. Denna process kallas för **feature learning**.

## Feature learning
Anta att vi har data $\boldsymbol{X} = (x_1, x_2, \dots, x_p)$ där vi kan skapa transformationer av data via en godtycklig funktion $h(\cdot)$. Det första gömda lagret kan exempelvis formuleras som en linjärkombination av $\boldsymbol{X}$. 

$$
  \begin{aligned}
  z_j = h(x) = \sum_{i = 1}^p w_{ij} x_i
  \end{aligned}
$$
där $w_{ij}$ är vikten som läggs på den $i$:te variabelns koppling till den $j$:te neuronen. Vanligtvis lägger vi till en **bias**-term till kombinationen [VARFÖR? FINNS DET NÅGON PRAKTISK ORSAK?]{style="color: red"}. 

Denna funktion blir dock fortfarande en linjär transformation, så hur kan vi då modellera något icke-linjärt? Med hjälp av många enkla icke-linjära funktioner kan vi skapa en komplex icke-linjär funktion. All detta tillsammans kan vi skriva funktionen som:

$$
  \begin{aligned}
  z_j = h(x) = \sigma\left(b_0 + \sum_{i = 1}^p w_{ij} x_i\right)
  \end{aligned}
$$ {#eq-hidden-neuron}
där $b_0$ är bias-termen och $\sigma(\cdot)$ är en så kallad **aktiveringsfunktion**.

Aktiveringsfunktionen har historiskt varit någon form av sigmoid funktion, det vill säga en differentierbar och s-formad kurva. Numera är **ReLu** eller dess varianter den vanligaste formen av aktiveringsfunktion. ReLu står för Rectified Linear Unit och beskriver en linjär funktion i det positiva området och en annan linjär funktion i det negativa området.

$$
  \begin{aligned}
  ReLu(x) = max(0, x)
  \end{aligned}
$$

```{r}
#| fig-width: 5
#| fig-height: 3
#| fig-cap: ReLu aktiveringsfunktion
#| label: fig-relu
#| out-width: "90%"
#| echo: false

x <- seq(-5, 5, length.out = 1000)

tibble(
  x = x
) |> 
  rowwise() |> 
  mutate(y = max(0, x)) |> 
  ggplot() + aes(x = x, y = y) + geom_line(linewidth = 1, color = "steelblue") + theme_bw()

```

Det finns många fördelar med att använda ReLu som aktiveringsfunktion till förmån för de historiska sigmoid-kurvorna. Bland annat undviker ofta ReLu att gradienten i optimeringsalgoritmen går mot 0, ett fenomen som kallas för **vanishing gradient**, samt att beräkningarna i optimeringen endast omfattar enkla beräkningar som jämförelser och addition. Däremot förekommer också några nackdelar såsom att funktionen är icke-differentierbar vid värdet 0 samt att nätverket ibland kan hamna i en situation där alla neuroner inte aktiveras ($ReLu(x) = 0$) och därigenom inte fortsätter att optimera. 

Det sista lagrets aktiveringsfunktion måste bestämmas utifrån responsvariabeln. För regression används identitetsfunktionen om vi tillåter värden från hela tallinjen eller en funktion såsom $exp()$ om vi bara tillåter positiva värden. För klassificering kan vi använda olika sigmoid-funktioner såsom den logistiska funktionen (se @sec-logistic-func) om responsvariabeln är binär eller **Softmax**-funktionen om responsvariabeln är nominell.

Softmaxfunktionen normaliserar outputlagrets värden enligt:

$$
  \begin{aligned}
  f_i = \sigma(\boldsymbol{z})_i = \frac{exp(z_i)}{\sum_{j = 1}^K exp(z_j)}
  \end{aligned}
$$

Vi kan se det som att det neurala nätverket från input till de gömda lagrena lär sig transformationer av de förklarande variablerna för att i sista lagret genomföra linjär/logistisk/multinomial regression på dessa.

**Universal approximation theorem** säger informellt att "En MLP med ett gömt lager och en icke-linjär aktiveringsfunktion kan approximera en godtycklig kontinuerlig eller diskret funktion med ett godtyckligt litet fel givet tillräckligt många gömda neuroner". Vad detta betyder i praktiken är att neurala nätverk är flexibla och givet en tillräckligt stor modell också har bra prestanda. När klassiska statistiska modeller inte kan hantera mängden observationer, ett stort antal parametrar, eller komplexa samband kan ett neuralt nätverk komma väl till pass för att lösa samma problem. 

Detta blir dock också till viss del en nackdel, ett neuralt nätverk [kräver mycket data]{.underline} för att lära sig komplexa funktioner samt att nätverket [lätt kan överanpassa träningsdata]{.underline}, men den absolut största nackdelen med neurala nätverk är att vi helt tappar den förklarande biten. Modellen blir en ["black box"]{.underline} som inte kan beskriva den faktiska effekt som en förklarande variabel har på responsvariabeln som vi är vana vid från vanlig regression.

:::{.callout-tip}
På senare tid har metoder utvecklats som utvärderar variablers påverkan på modellens prediktioner som till viss del kan användas för att beskriva effekten av en förklarande variabel på responsvariabeln. Bland annat finns SHAP och LIME (@salih2025 och @bobadilla2024) som ni kan läsa om på egen hand.
:::

## Optimering 
Till skillnad från de tidigare modellerna som vi introducerat, skapar optimering av ett neuralt nätverk ett nytt problem som måste lösas. Parametrarna som ska optimeras är nätverkets vikter (och bias) för varje lager men om vi skulle optimera vikterna lager för lager inser vi snabbt att vi inte har något sätt att mäta felet för något annat lager än det sista. Det är enbart för $f_i$ som vi har observerade värden som kan appliceras i en vald felfunktion. Vi behöver därför använda **backpropagation**, en metod som med hjälp av kedjeregler för derivator kan optimera vikterna även i början av nätverket.

:::{.callout-tip}
3Blue1Brown har en väldigt bra illustrativ serie om hur neurala nätverk fungerar, däribland en illustration av hur backpropagation arbetar inom optimeringen.

{{< video https://www.youtube.com/watch?v=Ilg3gGewQ5U&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=3 >}}
:::

För de komplexa problem som neurala nätverk ofta försöker lösa, krävs att vi använder mer komplexa optimeringsalgoritmer. Det finns också en ökande kostnad att beräkna den totala gradienten för alla nätverkets vikter vid varje iteration. Detta leder oss till nya problem och avvägningar som vi måste ta ställning till.

### Batch

Istället för att beräkna hela derivatan på en gång för alla datapunkter kan vi beräkna en väntevärdesriktigskattning av gradienten från ett slummässigt urval av data. Detta urval kallas för en **mini-batch** och tillåter att vi uppdaterar vikterna oftare (fler iterationer) med lite mer variation men utan samma beräkningskomplexitet. Större batcher ger mindre varians i gradientens skattning men blir dyrare att beräkna. 

I och med att skattningen inte blir den "sanna" gradienten kan vi också försäkra oss om att vi inte hamnar helt fel genom att minska inlärningshastigheten. Då förhindrar vi att en dålig skattning påverkar algoritmen mycket.

### Hyperparametrar
Inom neurala nätverk finns massvis med hyperparametrar, alltifrån nätverkets arkitektur; antalet gömda lager, neuroner i varje lager, aktiveringsfunktioner m.fl., till nätverkets optimering; batch-storleken, inlärningshastigheten, val av optimeringsalgoritm m.fl. 

En hyperparameter som hör till optimeringsdelen är **epoker**. En epok är en genomgång av all träningsdata där [LÄGG TILL MER OM EPOKER OCH DESS INNEBÖRD]{style="color: red"}

Valet av hyperparametrarnas värden för neurala nätverk är mycket svårt utan något exakt svar. Med hjälp av olika sökmetoder kan vi få en strukturerad jämförelse men det kommer i praktiken bestå av mycket trial and error. Det finns också många föreslagna nätverksarkitekturer från litteraturen sam förtränade modeller som kan anpassas om för nya problem vilket kan underlätta. För stora problem kan det ta lång tid att hitta bra hyperparametrar!

:::{.callout-tip}
En utav de större ramverken för neurala nätverk är Tensorflow. Det har också skapat ett [visualiseringsverktyg](https://playground.tensorflow.org/) där man kan leka runt med olika modeller och se vad som händer.
:::

**Stokastisk gradient descent** är en utveckling av gradient descent som använder sig av batches för att förenkla optimeringen. Som tidigare nämnt, behöver inlärningshastigheten ($\gamma$) justeras för att ta hänsyn till att vi endast tittar på ett slumpmässigt urval vid varje iteration istället för alla observationer. 

Det vanligaste är att vi justerar $\gamma$ med antalet iterationer enligt någon form av schema, $\gamma_1, \gamma_2, \gamma_3, \dots$, som uppfyller några krav. Till exempel $\sum_{k = 1}^\infty \gamma_k = \infty$ och $\sum_{k = 1}^\infty \gamma_k^2 < \infty$ som båda uppfylls om $\gamma_k = 1 / k$.

Backpropagation multiplicerar flera derviator med varandra (kedjeregeln) vilket lätt kan leda till försvinnande eller exploderande gradienter (eng. vanishing och exploding gradient). En försvinnande gradient inträffar när produkten av derivatorerna är nära 0 vilket leder till att vikterna inte uppdateras alls medan en exploderande gradient inträffar när produkten av derivatorerna är för stora vilket leder till instabil optimering. ReLu som aktiveringsfunktion hanterar båda dessa problem bättre än sigmoid-funktioner men det finns fortfarande tillfällen där även ReLu hamnar i dessa fällor.

Vi kan lägga till ytterliggare en hyperparameter i optimeringslagoritmen som vi kallar för **momentum** ($\alpha$) som beskriver hur mycket av den gamla derivatan som vi sparar i nästa iteration. 

$$
  \begin{aligned}
  v = \alpha \cdot v - \gamma_k \cdot \hat{\nabla L}
  \end{aligned}
$$
vilket sedan ger:

$$
  \begin{aligned}
  \theta_k = \theta_{k-1} + v
  \end{aligned}
$$
Detta tillåter oss att jämna ut stora steg så att en försvinnande eller exploderande gradient vid en iteration inte fullt ut inträffar.

[SKRIV UPP DENNA TIDIGARE SÅ ATT SKILLNADEN MELLAN MOMENTUM OCH INGEN BLIR TYDLIGARE. DETTA FUNKAR VÄL INTE MED EXPLODERANDE DÅ $\nabla$ HADE BLIVIT STOR REGARDLESS?]{style="color: color"}

Varje optimeringsalgoritm måste börja med några initiala värden på parametrarna. Dessa kallas för **startvärden**. Valet av startvärden påverkar algoritmen tillsammans med de övriga hyperparametrarna, i värsta fall kan vi med dåliga startvärden få stora problem. Eftersom ett nätverk ofta består av tusentals parametrar som vi måste skatta sätts dessa startvärden oftast slumpmässigt, antingen likformigt eller normalfördelat. Vi kan också låta algoritmen initialisera flera startvärden för att utforska en större del av felfunktionen. Detta gör att vi minskar risken att hamna i ett dåligt lokalt minimum.

Kan vara svårt att få till en bra learning rate som passar alla parametrar när vi använder SGD. En idé är att anpassa learning rate för varje parameter. **RMSProp** skalar om gradienten beroende på träningshistoriken så att vi tar större steg för de parametrar med små derivator och tar mindre steg för de parametrar med stora derivator. Metoden skalar med exponentiellt avtagande glidande medelvärden för tidigare gradienter. **ADAM** kan ses som en blandning av RMSProp och momentum. Finns ännu fler varianter, RMSProp och Adam är vanliga standardval för neurala nätverk och finns i de flesta paket.

[BATCHNORMALIZATION, REGULARISERING, DROPOUT? DET BLIR GANSKA MYCKET I DETTA KAPITEL REDAN.]{style="color: color"}

## Referenser {.unnumbered}







